version: "3.2"

services:
  arrears-action-api-unit-tests:
    image: arrears-action-api-unit-tests
    build:
      context: .
      dockerfile: ArrearsActionAPI.UnitTests/Dockerfile
    environment:
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
    links:
      - test-database
  
  test-database:
    image: test-database
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
      - 5432:5432
    env_file:
      - database.env