version: 2.1

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker-compose build arrears-action-api-unit-tests
      - run:
          name: Run tests
          command: docker-compose run arrears-action-api-unit-tests

workflows:
  build-and-test:
      jobs:
      - check